// **DO NOT EDIT THIS FILE**

const dotenv = require('dotenv');
const mongoose = require('mongoose');
const chalk = require('chalk');
dotenv.config();

const { Schema } = mongoose;
const MONGO_USER = process.env.MONGO_USER;
const MONGO_PASS = process.env.MONGO_DB_PASS;
const MONGO_DB = 'sauce-exercise';

const encoded_pass = `${encodeURI(MONGO_USER)}:${MONGO_PASS}`;
const mongo_uri =
  `mongodb+srv://${encoded_pass}@cluster0-c2jyp.mongodb.net/` +
  `${encodeURI(MONGO_DB)}?retryWrites=true&ssl_cert_reqs=CERT_NONE`;

mongoose.connect(mongo_uri, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

module.exports = {
  mongoose,
  Schema,
};
